In [3]:
#Version with final color references
import numpy as np
from skimage.color import rgb2hsv
import matplotlib.pyplot as plt
from skimage.segmentation import slic
from scipy.spatial.distance import cityblock

img=plt.imread("C:/Users/mihae/Documents/GitHub/mdasm-2024/images/PAT_29_40_561.png")[:,:,:3]
mask=plt.imread("C:/Users/mihae/Documents/GitHub/mdasm-2024/masks/PAT_29_40_561_mask.png")
#Extract the lesion from the whole picture, using the mask
lesion_coords = np.where(mask != 0)
min_x = min(lesion_coords[0])
max_x = max(lesion_coords[0])
min_y = min(lesion_coords[1])
max_y = max(lesion_coords[1])
cropped_lesion = img[min_x:max_x,min_y:max_y]
#Generate the slic of the image
segments = slic(cropped_lesion, n_segments=250, compactness=100)
colours=[[355, 83, 93], #red(pantone) - ready
         [5, 93, 100], #some other red - ready
         [30, 100, 59], #brown - ready
         [209, 24, 44], #black coral
         [210, 50, 80],  #some blue-gray
         [329,49,97], #persian pink - ready
         [350,25,100], #pink - ready
         [346,42,97], #sherbet pink - ready
         [354,89,61], #ruby red - ready
         [20,56,69], #brown sugar - ready
         [24,49,24], #bistre - dark brown - ready
         [50,48,99], # yellow(crayola)
         [0,2,76]] #white 
#Creating some colour bins
colours_bins=[0,0,0,0,0,0,0,0,0,0,0,0,0,0]
segment_means=[]
for segment_value in np.unique(segments):
        mask = segments == segment_value
        segment_pixels = cropped_lesion[mask]
        segment_mean = segment_pixels.mean(axis=0)
        segment_means.append(segment_mean)
sdt = segment_means
sdt = np.array(sdt)
ssr = rgb2hsv(sdt)
multip=np.array([360,100,100])
#finishing part of the rgb to hsv conversion
sss = ssr*multip
#run through each pixel in the slic
for items in sss:
    distance_color=[0,0,0,0,0,0,0,0,0,0,0,0,0]
    #if the v value of HSV is below 20, then it is black and goes to bin 5
    if int(items[2])<=25:
        colours_bins[13]+=1
    else:
        for itemsss in enumerate(colours):
            #Calculate the Manhattans distance between the current pixel and the defined colours
            distance_color[itemsss[0]]=cityblock(items, itemsss[1])
        smallest_dist=min(distance_color)
        for items in enumerate(distance_color):
            if items[1]==smallest_dist:
                colours_bins[items[0]]+=1
print(colours_bins)
thrashhold=0.05*sum(colours_bins)
counter=0

color_names=["red", 'brown', 'blue', 'pink', 'black', 'white']
colour_bins_new=[colours_bins[0]+colours_bins[1]+colours_bins[8], colours_bins[2]+colours_bins[9]+colours_bins[10],
                 colours_bins[3]+colours_bins[4], colours_bins[5]+colours_bins[6]+colours_bins[7], 
                 colours_bins[13], colours_bins[11]+colours_bins[12]]
for items in range(6):
    print(f'{colour_bins_new[items]} {color_names[items]} pixels')
for items in colour_bins_new:
    if items>thrashhold:
         counter+=1
print(sss)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 246, 2, 3, 1, 0]
0 red pixels
248 brown pixels
0 blue pixels
0 pink pixels
0 black pixels
4 white pixels
[[28.39080423 24.75319356 84.5831275 ]
 [27.47378111 28.00127566 82.8980267 ]
 [27.05141634 31.46528304 80.96751571]
 [26.17066473 35.38003862 78.07751894]
 [27.37182766 33.32981467 78.76843214]
 [29.79508013 28.49473953 82.72016048]
 [30.20346522 26.48696601 83.16565752]
 [32.57667571 26.78820789 82.93449879]
 [31.22146279 25.26459098 83.76502991]
 [30.89464635 23.60665947 85.15401483]
 [31.5358606  24.22749251 84.32255983]
 [29.50098664 23.63629043 84.80275273]
 [27.96231061 23.85870814 84.69466567]
 [28.23447973 23.43916744 83.79576802]
 [27.94367999 29.33685482 79.64881659]
 [26.7834717  33.19056332 78.733778  ]
 [25.05463243 36.67604625 76.01453066]
 [23.78570884 39.90757167 72.25215435]
 [23.68248135 40.31986296 71.66960239]
 [24.50817794 39.32804167 72.2743392 ]
 [26.08398646 36.07944548 76.40304565]
 [28.26761037 33.92377496 75.82249641]
 [30.5389

In [ ]:
# Initial version of the color references
def color_etraction(segments_mean_hsv ):
    colours_bins=[0,0,0,0,0,0,0,0,0,0,0]
    colours=[[355, 83, 93], #red(pantone) - 
         [5, 93, 100], #some other red - 
         [30, 100, 59], #brown - 
         [209, 24, 44], #black coral
         [210, 50, 80],  #some blue-gray
         [329,49,97], #persian pink - 
         [350,25,100], #pink - 
         [346,42,97], #sherbet pink - 
         [354,89,61], #ruby red - 
         [20,56,69]] #brown sugar - 
         #[24,49,24]] #bistre - dark brown - 
    multip=np.array([360,100,100])
    #finishing part of the rgb to hsv conversion
    segments_mean_hsv_scaled = segments_mean_hsv*multip
    for i in segments_mean_hsv_scaled:
        distance_color=[0,0,0,0,0,0,0,0,0,0]
        #if the v value of HSV is below 25, then it is black and goes to bin 5
        if int(i[2])<=25:
            colours_bins[10]+=1
        else:
            for j in enumerate(colours):
                #Calculate the Manhattans distance between the current pixel and the defined colours
                distance_color[j[0]]=cityblock(i, j[1])
            smallest_dist=min(distance_color)
            for k in enumerate(distance_color):
                if k[1]==smallest_dist:
                    colours_bins[k[0]]+=1
        #print(colours_bins)
        #thrashhold=0.05*
        #counter=0
    colour_bins_new=[colours_bins[0]+colours_bins[1]+colours_bins[8], colours_bins[2]+colours_bins[9], colours_bins[3]+colours_bins[4], colours_bins[5]+colours_bins[6]+colours_bins[7], colours_bins[10]]
    colour_bins_new/=sum(colours_bins)
    return colour_bins_new
    
